name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
      - 'resources/STUB_VERSION'
      - 'docs/**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.1013'

      - name: Check if namespaces are clean
        run: clojure -M:clojure-lsp clean-ns --dry

      - name: Check if namespaces are formatted
        run: clojure -M:clojure-lsp format --dry

      - name: Check if namespaces have no diagnostics
        run: clojure -M:clojure-lsp diagnostics

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [8, 11, 15, 17]
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.1013'

      - name: Run tests
        run: clojure -M:test

  graalvm-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.1013'

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: 21.3.0
          java: java11

      - name: Install native-image component
        run: |
          gu install native-image

      - name: Build Linux native image
        env:
          STUB_XMX: "-J-Xmx6g"
        run: |
          clojure -T:build native

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: stub-native
          path: stub
